version: "3.8"

services:
  mariadb:
    container_name: mariadb

    build:
      context: ./requirements/mariadb
      dockerfile: ./Dockerfile
      args:
        - MARIADB_ADMIN
        - MARIADB_ADMIN_PW
        - MARIADB_USER
        - MARIADB_USER_PW
        - MARIADB_NAME
        - GITEA_DB
        - GITEA_USER
        - GITEA_USER_PW

    restart: always

    volumes:
      - v_wpdb:/var/lib/mysql

    networks:
      nw-db:
        aliases:
          - $MARIADB_HOST

    env_file:
      - .env

  wordpress:
    container_name: wordpress

    build:
      context: ./requirements/wordpress
      dockerfile: ./Dockerfile

    restart: always

    volumes:
      - v_wp:/var/www/html

    networks:
      nw-db: {}
      nw-redis:
        aliases:
          - $REDIS_HOST
      nw-ftp: {}
      nw-nginx:
        aliases:
          - $WP_HOST

    env_file:
      - .env

    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy


  nginx:
    container_name: nginx

    build:
      context: ./requirements/nginx
      dockerfile: ./Dockerfile
      args:
        - DOMAIN_NAME
        - EMAIL
        - PORT_ADMINER

    restart: always

    ports:
      - "443:443"

    volumes:
      - v_wp:/var/www/html

    networks:
      nw-nginx: {}

    env_file:
      - .env

    depends_on:
      wordpress:
        condition: service_healthy


  redis:
    container_name: redis

    build:
      context: ./requirements/bonus/redis
      dockerfile: ./Dockerfile
      args:
        - REDIS_HOST
        - REDIS_PW
        - PORT_REDIS

    restart: always

    networks:
      nw-redis:
        aliases:
          - $REDIS_HOST

    env_file:
      - .env

  vsftpd:
    container_name: vsftpd

    build:
      context: ./requirements/bonus/vsftpd
      dockerfile: ./Dockerfile
      args:
        - DOMAIN_NAME
        - EMAIL
        - FTP_USER
        - PORT_FTP_MIN
        - PORT_FTP_MAX

    restart: always

    ports:
      - "20:20"
      - "21:21"
      - "$PORT_FTP_MIN-$PORT_FTP_MAX:$PORT_FTP_MIN-$PORT_FTP_MAX"

    volumes:
      - v_wp:/var/ftp

    networks:
      nw-ftp:
        aliases:
          - $FTP_HOST

    env_file:
      - .env

    depends_on:
      wordpress:
        condition: service_healthy

  adminer:
    container_name: adminer

    build:
      context: ./requirements/bonus/adminer
      dockerfile: ./Dockerfile
      args:
        - PORT_ADMINER

    restart: always

    networks:
      nw-nginx:
        aliases:
          - $ADMINER_HOST
      nw-db: {}

    env_file:
      - .env


  gitea:
    container_name: gitea

    build:
      context: ./requirements/bonus/gitea
      dockerfile: ./Dockerfile
      args:
        - MARIADB_HOST
        - GITEA_DB
        - GITEA_USER
        - GITEA_USER_PW
        - EMAIL

    restart: always

    ports:
      - "3000:3000"

    volumes:
      - v_git:/var/lib/gitea/git

    networks:
      nw-db: {}

    env_file:
      - .env

    depends_on:
      mariadb:
        condition: service_healthy


  static:
    container_name: static

    build:
      context: ./requirements/bonus/static
      dockerfile: ./Dockerfile

    restart: always

    ports:
      - "8000:8000"


networks:
  nw-db:
    driver: bridge
  nw-nginx:
    driver: bridge
  nw-redis:
    driver: bridge
  nw-ftp:
    driver: bridge

volumes:
  v_wpdb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $DATA_PATH/wpdb

  v_wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $DATA_PATH/wp

  v_git:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $DATA_PATH/git
