## EXAMPLE CODE

version: "3.9"

networks:
  front-connection:
    driver: bridge
  db-connection:
    driver: bridge

volumes:
  v_wordpressdb:
    driver: local
  v_wp:
    driver: local


services:
  # mariadb:
  #   container_name: mariadb

  #   build:
  #     context: ./requirements/mariadb
  #     dockerfile: ./Dockerfile

  #   restart: always

  #   # ports:
  #   #   - "${PORT_MARIADB}:${PORT_MARIADB}"

  #   volumes:
  #     - v_wordpressdb:/var/www/html/wpdb

  #   networks:
  #     - db-connection

  #   environment:
  #     - MARIADB_USER=${MARIADB_USER}
  #     - MARIADB_PASSWORD=${MARIADB_PASSWORD}
  #     - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
  #     - MARIADB_DATABASE=${MARIADB_DATABASE}


  # wordpress:
  #   container_name: wordpress

  #   build:
  #     context: ./requirements/wordpress
  #     dockerfile: ./Dockerfile

  #   restart: always

  #   # ports:
  #   #   - "${PORT_WORDPRESS}:${PORT_WORDPRESS}"
  #   #   - "${PORT_MARIADB}:${PORT_MARIADB}"

  #   volumes:
  #     - v_wp:${WORDPRESS_PATH}

  #   networks:
  #     - front-connection
  #     - db-connection

  #   environment:
  #     - WORDPRESS_PATH=${WORDPRESS_PATH}
  #     - WORDPRESS_URL=${WORDPRESS_URL}
  #     - WORDPRESS_TITLE=${WORDPRESS_TITLE}
  #     - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
  #     - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
  #     - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
  #     - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
  #     - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
  #     - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
  #     - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}

  #   depends_on:
  #     - mariadb


  # nginx:
  #   container_name: nginx

  #   build:
  #     context: ./requirements/nginx
  #     dockerfile: ./Dockerfile

  #   restart: always

  #   ports:
  #     - "${PORT_NGINX}:${PORT_NGINX}"
  #     # - "${PORT_WORDPRESS}:${PORT_WORDPRESS}"

  #   volumes:
  #     - v_wp:/var/www/html

  #   networks:
  #     - front-connection

  #   environment:
  #     - TZ=Asia/Seoul

  #   depends_on:
  #     - wordpress


  nginx:
    container_name: nginx

    build:
      context: ./requirements/nginx
      dockerfile: ./Dockerfile

    restart: always

    ports:
      - "${PORT_NGINX}:${PORT_NGINX}"
      # - "${PORT_WORDPRESS}:${PORT_WORDPRESS}"

    volumes:
      - v_wp:/var/www/html

    networks:
      - front-connection

    environment:
      - TZ=Asia/Seoul

    # depends_on:
    #   - wordpress
