## EXAMPLE CODE

version: "3.9"

networks:
  nw-db:
    driver: bridge
  nw-cgi:
    driver: bridge

volumes:
  v_wpdb:
    driver: local
  v_wp:
    driver: local


services:
  mariadb:
    container_name: mariadb

    build:
      context: ./requirements/mariadb
      dockerfile: ./Dockerfile

    restart: always

    volumes:
      - v_wpdb:/var/www/html/wpdb

    networks:
      - nw-db

    env_file:
      - .env


  wordpress:
    container_name: wordpress

    build:
      context: ./requirements/wordpress
      dockerfile: ./Dockerfile

    restart: always

    volumes:
      - v_wp:${WP_PATH}

    networks:
      - nw-db
      - nw-cgi

    env_file:
      - .env

    depends_on:
      mariadb:
        condition: service_healthy


  nginx:
    container_name: nginx

    build:
      context: ./requirements/nginx
      dockerfile: ./Dockerfile

    restart: always

    ports:
      - "${PORT_NGINX}:${PORT_NGINX}"

    volumes:
      - v_wp:/var/www/html

    networks:
      - nw-db
      - nw-cgi

    environment:
      - TZ=Asia/Seoul

    depends_on:
      wordpress:
        condition: service_healthy
