## EXAMPLE CODE

version: "3.9"

networks:
#   front-connection:
#     driver: bridge
  db-connection:
    driver: bridge

services:
  # nginx:
  #   container_name: nginx
  #   image: alpine
  #   restart: always
  #   ports: 
  #     - "${PORT_NGINX}:${PORT_NGINX}"
  #   volumes:
  #     - ./wordpress/html:/var/www/wordpress
  #   networks:
  #     - front-connection
  #   environment:
  #     - TZ=Asia/Seoul
  #   depends_on:
  #     - wordpress
  #     - mariadb

  # wordpress:
  #   container_name: wordpress
  #   image: alpine
  #   restart: always
  #   ports:
  #       - "${PORT_WORDPRESS}:${PORT_WORDPRESS}"
  #       - "${PORT_MARIADB}:${PORT_MARIADB}"
  #   volumes:
  #       - ./wordpress/html:/var/www/wordpress
  #   networks:
  #     - front-connection
  #     - db-connection
  #   environment:
  #       - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
  #       - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
  #       - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
  #       - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
  #   depends_on:
  #     - mariadb

  mariadb:
    container_name: mariadb
    image: alpine
    restart: always
    ports:
        - "${PORT_WORDPRESS}:${PORT_WORDPRESS}"
        - "${PORT_MARIADB}:${PORT_MARIADB}"
    # volumes:
    #   - ./mariadb/wpdb:/wpdb
    networks:
      - db-connection
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}