## EXAMPLE CODE

version: "3.9"

networks:
  local-network:
    driver: bridge
  # front-connection:
  #   driver: bridge
  # db-connection:
  #   driver: bridge

volumes:
  v_wordpressdb:
    driver: local
  v_wp:
    driver: local


services:
  mariadb:
    container_name: mariadb

    build:
      context: ./requirements/mariadb
      dockerfile: ./Dockerfile

    restart: always

    # ports:
    #   - "${PORT_MARIADB}:${PORT_MARIADB}"

    volumes:
      - v_wordpressdb:/var/www/html/wpdb

    networks:
      - local-network
      # - db-connection

    env_file:
      - .env


  wordpress:
    container_name: wordpress

    build:
      context: ./requirements/wordpress
      dockerfile: ./Dockerfile

    restart: always

    # ports:
    #   - "${PORT_WORDPRESS}:${PORT_WORDPRESS}"
    #   - "${PORT_MARIADB}:${PORT_MARIADB}"

    volumes:
      - v_wp:${WORDPRESS_PATH}

    networks:
      - local-network
      # - front-connection
      # - db-connection

    env_file:
      - .env

    depends_on:
      - mariadb


  nginx:
    container_name: nginx

    build:
      context: ./requirements/nginx
      dockerfile: ./Dockerfile

    restart: always

    ports:
      - "${PORT_NGINX}:${PORT_NGINX}"
      # - "${PORT_WORDPRESS}:${PORT_WORDPRESS}"

    volumes:
      - v_wp:/var/www/html

    networks:
      - local-network
      # - front-connection

    environment:
      - TZ=Asia/Seoul

    depends_on:
      - wordpress
